name: Release
on:
  push:
    branches:
      - main
      - test
jobs:
  test:
    name: 'Build and check code before release'
    uses: ./.github/workflows/build-and-run-check-workflow.yml

  release:
    name: 'Prepare new version'
    uses: fingerprintjs/dx-team-toolkit/.github/workflows/release-server-sdk.yml@v1
    with:
      language: flutter
      language-version: '3.x'
    secrets:
      GH_RELEASE_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
