name: Release
on:
  push:
    branches:
      - main
      - test
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install and set Flutter version
        uses: subosito/flutter-action@0c3f14223a08fa950c8a4c00bcfb834e65744135
        with:
          flutter-version: '3.3.8'
      - name: Restore packages
        run: flutter pub get
      - name: Create .env.local
        run: cp ./example/.env ./example/.env.local
        shell: bash
      - name: Analyze
        run: flutter analyze
      - name: Run tests
        run: flutter test
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@91ab76a4a393a8d0c4739e9aea1818b56bc953ea
        with:
          extra_plugins: |
            @semantic-release/exec@6.0.3
            conventional-changelog-conventionalcommits@5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_GH_TOKEN }}
